### ISSUE TITLE
Bounding box too small contrary to shown in book

### ISSUE THREAD

**Issue by mnauf** [PacktPublishing/PyTorch-Computer-Vision-Cookbook#10]
Bounding boxes appear too small before resizing in Ch4: ![Screenshot](https://imgur.com/nAP53pj.png)

**Comment by mave5** [comment]
Thanks @mnauf  for reporting this. I think this must be a typo in the book where we pass ```w,h=(150,150)``` to ```show_img_label``` function, and the book figure was perhaps generated using larger values for ```h,w```.
 Try larger values like ```w,h=(300,300)``` to get a bigger bounding box on the original image.

**Comment by mave5** [comment]
I guess resolved.
