### ISSUE TITLE
Pirated copy of your book?

### ISSUE THREAD

**Issue by samsont** [PacktPublishing/PyTorch-Computer-Vision-Cookbook#12]
I saw your book here: https://circuitnoob.com/pytorch-computer-vision-cookbook-over-70-recipes-to-solve-computer-vision-and-image-processing-problems-using-pytorch-1-x/ .

I wanted to make sure that was ok. Is it allowed to be there?

**Comment by mave5** [comment]
thanks for the heads up. Of course, it is illegal.  @ManikandanKurup-Packt

**Comment by mravendi** [comment]
n/a

**Comment by ManikandanKurup-Packt** [comment]
@samsont Thank you for bringing this to our attention.
@mravendi I have informed our anti-piracy team and they'll report it and take it down.

**Comment by samsont** [comment]
I run this facebook group with lots of people:
https://www.facebook.com/groups/ComputerVisionGroup

Someone had posted a bunch of books; we took down her posts. If It is
helpful, I can look up her username.

And, you guys should feel free to post. We have 50,000 people. It looks
like you have some great work.

-- Samson
