### ISSUE TITLE
Training yolo model with different image size

### ISSUE THREAD

**Issue by mikeyEcology** [PacktPublishing/PyTorch-Computer-Vision-Cookbook#14]
Hi, 
I'm using the code from Chapter 5 as a guide to train a yolo model, but I'm struggling with trying to use an image of different dimensions than the 416 that is used in the book. I've edited the `create_layers` function so that it takes image size as an input and passes it to `YOLOLayer`, but when I try to train a model, I get the error:

>  File "<ipython-input-7-a58b570b06bf>", line 97, in forward
    x = torch.cat([layer_outputs[int(l_i)]
RuntimeError: Sizes of tensors must match except in dimension 1. Got 34 and 33 in dimension 2

Do you have any suggestions for using a different size image? I could not find any details about this in the text book either. Thank you

**Comment by mave5** [comment]
Hi @mikeyEcology 
What is the size of your images?
You can have images in different sizes. In fact, the coco dataset has images of all kinds of sizes.
The transformer function will resize the input image to 416 by 416 using the pad_to_square function.

```python

def transformer(image, labels, params):
    if params["pad2square"] is True:
        image,labels= pad_to_square(image, labels)
    
    image = TF.resize(image,params["target_size"])

    if random.random() < params["p_hflip"]:
        image,labels=hflip(image,labels)

    image=TF.to_tensor(image)
    targets = torch.zeros((len(labels), 6))
    targets[:, 1:] = torch.from_numpy(labels)
    
    return image, targets
```

**Comment by mikeyEcology** [comment]
I was referring to using a different image size to train the model (I don't want it resized to 416x416). I've solved this by finding that I can use an image size as long as it is divisible by 32.
