### ISSUE TITLE
Page 174, When i run get_coco_dataset.sh, get_coco_dataset.sh: 29: get_coco_dataset.sh: Syntax error: "(" unexpected

### ISSUE THREAD

**Issue by leeyunhome** [PacktPublishing/PyTorch-Computer-Vision-Cookbook#15]
Hello,

get_coco_dataset.sh: 29: get_coco_dataset.sh: Syntax error: "(" unexpected
Can you tell me how to solve this problem?

Thank you.

**Comment by mave5** [comment]
@leeyunhome  How do you run get_coco_dataset.sh? on windows or Linux?

**Comment by leeyunhome** [comment]
> @leeyunhome How do you run get_coco_dataset.sh? on windows or Linux?

Hello?

Linux (Ubuntu 18.04)

Thank you.

**Comment by mave5** [comment]
try 
```bash data/get_coco_dataset.sh```
or ```bash get_coco_dataset.sh```
it should be fixed.
