### ISSUE TITLE
AMD Grand challenge download forbidden

### ISSUE THREAD

**Issue by ktdiedrich** [PacktPublishing/PyTorch-Computer-Vision-Cookbook#2]
Even after signing into a free account the Download link https://amd.grand-challenge.org/download/ says "Forbidden"

**Comment by ssshhhubh** [comment]
http://ai.baidu.com/broad/download
try this out

**Comment by mave5** [comment]
If you fill out the signing form and join the competition, you will get access to the dataset within couple of days. Let me know if you still have any issue.

**Comment by rahiakela** [comment]
> http://ai.baidu.com/broad/download
> try this out

Please send me exact URL, it is accessible from Google Colab but not from browser. It is blocked by Indian govt.
