### ISSUE TITLE
lacking data

### ISSUE THREAD

**Issue by sushil79g** [PacktPublishing/PyTorch-Computer-Vision-Cookbook#3]
I don't see any datafiles. please, can you upload those too? thank you

**Comment by mave5** [comment]
can you elaborate? which chapter?

**Comment by sushil79g** [comment]
In chapter 2, train_labels CSV is imported but I didn't find those file

**Comment by mave5** [comment]
That is part of the data that you need to download as instructed in the book.

**Comment by mravendi** [comment]
issue resolved
